// Type definitions for GoopLum Agents feature
// Now using LangGraph Assistants API

// ─────────────────────────────────────────────────────────────────────────────
// ASSISTANT TYPES (LangGraph Assistants API)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Configurable fields stored in an Assistant's config
 * These are read by make_agent() at runtime to build the agent
 */
export interface AssistantConfigurable {
  model_preset: string;
  instructions: string;
  flow_tool_ids?: string[];
  gumcp_services?: string[];
}

/**
 * Assistant config wrapper
 */
export interface AssistantConfig {
  configurable: AssistantConfigurable;
}

/**
 * Assistant response from LangGraph Assistants API
 * Represents a custom AI agent with configurable prompt, model, and tools
 */
export interface Assistant {
  assistant_id: string;
  graph_id: string; // Always 'custom_agent' for our agents
  name: string;
  config: AssistantConfig;
  created_at: string;
  updated_at: string;
  metadata?: Record<string, unknown>;
}

/**
 * Request body for creating a new assistant
 */
export interface AssistantCreateRequest {
  graph_id: "custom_agent";
  name: string;
  config: AssistantConfig;
  metadata?: Record<string, unknown>;
}

/**
 * Request body for updating an assistant
 * Note: LangGraph requires full config, not partial updates
 */
export interface AssistantUpdateRequest {
  name?: string;
  config?: AssistantConfig;
  metadata?: Record<string, unknown>;
}

// ─────────────────────────────────────────────────────────────────────────────
// DISCOVERY TYPES (still served by /agents/* endpoints)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Model preset available for agents
 * Examples: claude-sonnet, gpt-4o, gemini-flash
 */
export interface ModelPreset {
  name: string;
  provider: string;
  model: string;
  description: string;
}

/**
 * Response from guMCP services endpoint
 */
export interface GumcpServicesResponse {
  services: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// THREAD TYPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Thread associated with an assistant
 * Uses LangGraph SDK thread with assistant_id in metadata
 */
export interface AssistantThread {
  thread_id: string;
  assistant_id: string;
  created_at: string;
  updated_at: string;
  /** Preview text from the first user message */
  preview?: string;
  metadata: Record<string, unknown>;
  /** Thread values including messages (from search response) */
  values?: {
    messages?: Array<{
      content: string | Array<{ type: string; text?: string }>;
      type: string;
      [key: string]: unknown;
    }>;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// ARTIFACT TYPES (for handling tool responses in chat)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Artifact returned by flow execution tool
 * Contains run_id pre-generated by agent for execute-stream
 */
export interface FlowExecutionRequestArtifact {
  type: "flow_execution_request";
  flow_id: string;
  flow_name: string;
  run_id: string;
  parameters: Record<string, unknown>;
}

/**
 * Artifact returned by flow compiler (Goopie)
 */
export interface FlowCompilerArtifact {
  flow_id: string;
  flow_name: string;
  flow_description: string;
  flow_explanation: string;
}
